<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>306f8c64-3407-47a9-bbe9-b1e30e174c64</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart_sauce_labs_fleece_jacket</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#add-to-cart-sauce-labs-fleece-jacket</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'add-to-cart-sauce-labs-fleece-jacket') and equals(@name,'add-to-cart-sauce-labs-fleece-jacket') and equals(@class,'btn btn_primary btn_small btn_inventory')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_primary btn_small btn_inventory</value>
        <webElementGuid>2dd01c90-cac6-4f10-b88e-446ae897b746</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-fleece-jacket</value>
        <webElementGuid>31676f62-93e8-4766-975f-c3f6ac77d561</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>add-to-cart-sauce-labs-fleece-jacket</value>
        <webElementGuid>4400d6ed-4973-4a5d-9dac-fe03a0c62141</webElementGuid>
    </webElementProperties>
</WebElementEntity>